import Head from "next/head";
import Header from "../components/Header";
import Section from "../components/Section";
import Description from "../components/Description";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Adventure Parallax</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Section />
      <Description />
      <Footer />
    </>
  );
}
